baseURL = "http://whirlwind-lang.dev/"
languageCode = "en-us"
title = "Whirlwind Docs"
theme = "learn"

[params]
    author = "Jordan Gaines"

    description = "Documentation for Whirlwind Programming Language"

    themeVariant = "blue"

    titleSeparator = "|"

