baseURL = "http://whirlwind-lang.dev/"
languageCode = "en-us"
title = "Whirlwind Docs"
theme = "book"

[params]
    BookTheme = "light"

    BookLogo = 'favicon.png'

    BookRepo = "https://github.com/ComedicChimera/whirlwind-lang.dev"

    BookComments = false

