baseURL = "http://whirlwind-lang.dev/"
languageCode = "en-us"
title = "Whirlwind"
theme = "docdock"
DefaultContentLanguage = "en"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
    editURL = "https://github.com/ComedicChimera/whirlwind-lang.dev/edit/master/content"
    themeStyle = "flex"
    
[outputs]
    home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
    name = "<i class='fa fa-download'></i> <label>Install</label>"
    url = "/install"
    weight = 1

[[menu.shortcuts]]
    name = "<i class='fa fa-github'></i> <label>Language Github</label>"
    url = "https://github.com/ComedicChimera/Whirlwind"
    weight = 2



