version: '3'
services:
  app:
    env_file: .env
    build: '.'
    ports:
     - '8080:5000'
    volumes:
     - ./static:/static
     - ./templates:/templates
    environment:
      DB_URI: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:3306/whirlwind_lang_org"
  db:
    env_file: .env
    image: postgres
    restart: always
    volumes: 
      - "./db:/var/lib/postgresql"
    ports:
      - "5432"




     